GIFS = (
    "CgACAgQAAxkBAAILhmBPVhvmLeQ7x0BUNygOsf5-qPlvAAI0AgAC3-rlUSFDZdjcYBnbHgQ",
    "CgACAgQAAxkBAAILhWBPVg9uSegny8s7C8HuVzGjUHCmAAK7AgACG01UUtbeIy3r78nBHgQ",
    "CgACAgQAAxkBAAILhGBPVgnTNBPxTrcKAbrE4j56oBiKAAKNAgACzzlNUjhN2BrAcRycHgQ", 
    "CgACAgQAAxkBAAILg2BPVfSA07AS5F8Z3VakA3mWi5JKAAJJAgACo7TlUTEO6b3HnInuHgQ",
    "CgACAgQAAxkBAAILgmBPVeneOMi3AhcR233iRWkYCVDVAALSAgACYk9dUu7Lw_yDOCUmHgQ", 
    "CgACAgQAAxkBAAILgWBPVeK6FKgLa6YlyKGhInoE7KSwAAKiAgACF5Q8UhjAzTtbZO20HgQ",
    "CgACAgQAAxkBAAILgGBPVc6FwZXpegno43bJBr2rZxd7AAJSAgAC5_-cUk-i1y9sSL-hHgQ", 
    "CgACAgQAAxkBAAILf2BPVcQDrPhpX6JXs_MB12R00u_ZAAIwAgACQAitUQnlm-veY3i6HgQ",
) 
